# Generated by Django 3.2.8 on 2021-10-15 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testo_domanda', models.CharField(max_length=200)),
                ('data', models.DateTimeField(verbose_name='data pubblicazione')),
            ],
        ),
        migrations.CreateModel(
            name='Risposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testo_risposta', models.CharField(max_length=200)),
                ('voto', models.IntegerField(default=0)),
                ('domanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.domanda')),
            ],
        ),
    ]
