# Generated by Django 3.2.8 on 2021-10-15 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_domanda_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=40)),
                ('data', models.DateTimeField(verbose_name='data categoria')),
            ],
        ),
        migrations.AlterField(
            model_name='domanda',
            name='categoria',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='polls.categoria'),
            preserve_default=False,
        ),
    ]
